sudo: false
language: node_js
addons:
  firefox: "48.0"
cache:
  directories:
  - $HOME/.npm
  - node_modules/selenium-standalone/.selenium # cache downloaded binaries
notifications:
  email: false
node_js:
  - '6'
before_install:
  - npm i -g npm@^3
before_script:
  - npm prune
  # headless testing with firefox
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
env:
  matrix:
    - CLIENT=selenium:firefox
    - CLIENT=saucelabs:chrome
